use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();
    emit_embedded_pets();
}

fn emit_embedded_pets() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let pets_dir = manifest_dir.join("../pets");
    println!("cargo:rerun-if-changed={}", pets_dir.display());

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let output_path = out_dir.join("embedded_pets.rs");

    let mut files = Vec::new();
    collect_files(&pets_dir, &pets_dir, &mut files);
    files.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs\n");
    generated.push_str("const EMBEDDED_BUILTIN_FILES: &[EmbeddedBuiltinFile] = &[\n");
    for (rel_path, abs_path) in files {
        let abs = abs_path
            .canonicalize()
            .unwrap_or(abs_path)
            .to_string_lossy()
            .replace('\\', "\\\\")
            .replace('"', "\\\"");
        let rel = rel_path.replace('\\', "/").replace('"', "\\\"");
        let _ = writeln!(
            generated,
            "    EmbeddedBuiltinFile {{ rel_path: \"{rel}\", bytes: include_bytes!(\"{abs}\") }},"
        );
    }
    generated.push_str("];\n");

    fs::write(output_path, generated).expect("write embedded_pets.rs");
}

fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if file_type.is_dir() {
            collect_files(root, &path, out);
            continue;
        }
        if !file_type.is_file() {
            continue;
        }
        let Ok(rel_path) = path.strip_prefix(root) else {
            continue;
        };
        out.push((rel_path.to_string_lossy().to_string(), path));
    }
}
